name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Remove old app directory but keep application.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cp ~/highteenday-back-server/src/main/resources/application.properties ~/application.properties || true
            rm -rf ~/highteenday-back-server

      - name: Upload Spring Boot App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "~/highteenday-back-server"
          rm: false
          overwrite: true
          strip_components: 0

      - name: Install Java 17 and PM2 on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! java -version &>/dev/null; then
              echo "Java not found. Installing OpenJDK 17..."
              sudo apt update
              sudo apt install -y openjdk-17-jdk
            else
              echo "Java is already installed."
            fi

            JAVA_PATH=$(readlink -f /usr/bin/java | sed "s:/bin/java::")
            echo "Detected JAVA_HOME as $JAVA_PATH"
            echo "export JAVA_HOME=$JAVA_PATH" >> ~/.bashrc
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> ~/.bashrc

            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing PM2..."
              sudo apt install -y npm
              sudo npm install -g pm2
            else
              echo "PM2 is already installed."
            fi



      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mv ~/application.properties ~/highteenday-back-server/src/main/resources/

            cd ~/highteenday-back-server
            chmod +x ./gradlew
            
            ./gradlew build -x test

            pm2 delete highteenday-backend || true

            pm2 start java --name "highteenday-backend" -- -jar build/libs/highteenday-backend-0.0.1-SNAPSHOT.jar -Dserver.address=0.0.0.0 -Dserver.port=8080

            pm2 save

            echo "✅ Spring Boot 서버가 PM2로 실행되었습니다."
