name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Remove old app directory but keep application.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cp ~/highteenday-back-server/src/main/resources/application.properties ~/application.properties || true
            rm -rf ~/highteenday-back-server

      - name: Upload Spring Boot App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "~/highteenday-back-server"
          rm: false
          overwrite: true
          strip_components: 0

      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

            mv ~/application.properties ~/highteenday-back-server/src/main/resources/

            cd ~/highteenday-back-server
            ./gradlew build

            pkill -f 'java -jar' || true
            nohup java -jar ~/highteenday-back-server/*.jar > ~/highteenday-back-server/app.log 2>&1 &
