name: Spring Boot CI/CD

on:
  push:
    branches: [ feature/user-security-action ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew build -x test

      - name: Upload .jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USER }}
          key: ${{ secrets.RASP_SSH_KEY }}
          port: ${{ secrets.RASP_PORT }}
          source: "build/libs/highteenday-backend-0.0.1-SNAPSHOT.jar"
          target: "/home/rasp-user/back-end"

      - name: Restart backend service with systemctl
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USER }}
          key: ${{ secrets.RASP_SSH_KEY }}
          port: ${{ secrets.RASP_PORT }}
          script: |
            sudo mv /home/rasp-user/back-end/build/libs/highteenday-backend-0.0.1-SNAPSHOT.jar /home/rasp-user/back-end/highteenday-backend-0.0.1-SNAPSHOT.jar
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl restart highteenday-backend.service
            sudo systemctl status highteenday-backend.service --no-pager
            echo "✅ Spring Boot 서버 실행 완료"
