name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Remove old app directory but keep application.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cp ~/highteenday-back-server/src/main/resources/application.properties ~/application.properties || true
            rm -rf ~/highteenday-back-server

      - name: Upload Spring Boot App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "~/highteenday-back-server"
          rm: false
          overwrite: true
          strip_components: 0

      - name: Install Java 17 on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Java 17 설치 여부 확인
            if ! java -version &>/dev/null; then
              echo "Java not found. Installing OpenJDK 17..."
              sudo apt update
              sudo apt install -y openjdk-17-jdk
            else
              echo "Java is already installed."
            fi

            # 설치된 Java 경로 확인 및 환경 변수 설정
            JAVA_PATH=$(readlink -f /usr/bin/java | sed "s:/bin/java::")
            echo "Detected JAVA_HOME as $JAVA_PATH"
            echo "export JAVA_HOME=$JAVA_PATH" >> ~/.bashrc
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> ~/.bashrc


      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mv ~/application.properties ~/highteenday-back-server/src/main/resources/

            cd ~/highteenday-back-server
            chmod +x ./gradlew
            
            ./gradlew build -x test
            
            pkill -f 'java -jar' || true
            nohup java -jar ~/highteenday-back-server/*.jar > ~/highteenday-back-server/app.log 2>&1 &
              
            sleep 5
            echo "✅ Spring Boot 서버 실행 완료"
